Cleaned up the important code a bit

diff --git a/dsort b/dsort
--- a/dsort
+++ b/dsort
@@ -120,9 +120,6 @@ while read -r line; do
     fi
 
     dst="$HOME/$line"
-    if [[ -z $SIMULATE && -n $MKDIR ]]; then
-        mkdir -- -p "$dst"
-    fi
 
     if [[ -n $MV_OPTS ]]; then
         for (( i = 0; i < count; ++i )); do
@@ -132,11 +129,19 @@ while read -r line; do
         done
     fi
 
-    if [[ -z $SIMULATE && -n $MKDIR && ! -d $dst ]]; then
-        echo "$EXE: Failed to create directory $dst" >&2
-    elif [[ -z $SIMULATE && ! -d $dst ]]; then
-        echo "$EXE: $dst does not exist" >&2
-    elif [[ -n $SIMULATE ]] && (( count != 0 )); then
+    if [[ -z $SIMULATE && $count -gt 0 ]]; then
+        if [[ -n $MKDIR ]]; then
+            mkdir -- -p "$dst"
+        fi
+
+        if [[ -n $MKDIR && ! -d $dst ]]; then
+            echo "$EXE: Failed to create directory $dst" >&2
+        elif [[ ! -d $dst ]]; then
+            echo "$EXE: $dst does not exist" >&2
+        else
+            mv $MV_OPTS -- "${files[@]}" "$dst"
+        fi
+    elif [[ $count -gt 0 ]]; then
         printf "%b\n" "Moving $count file(s) to $dst:"
         for file in "${files[@]}"; do
             if [[ -n $MV_OPTS && -f $dst/${file##*/} ]]; then
@@ -145,8 +150,6 @@ while read -r line; do
                 echo " $file"
             fi
         done
-    elif (( count != 0 )); then
-        mv $MV_OPTS -- "${files[@]}" "$dst"
     fi
 
     (( src_read = 0))
